.PHONY: help zappa-shell
.DEFAULT_GOAL := help
THIS_FILE := $(lastword $(MAKEFILE_LIST))
AWS_PROFILE ?= default

define PRINT_HELP_PYSCRIPT
import re, sys

for line in sys.stdin:
	match = re.match(r'^([a-zA-Z_-]+):.*?## (.*)$$', line)
	if match:
		target, help = match.groups()
		print("%-20s %s" % (target, help))
endef
export PRINT_HELP_PYSCRIPT

help:
	@python -c "$$PRINT_HELP_PYSCRIPT" < $(MAKEFILE_LIST)

zappa-shell:  ## enter Zappa shell
	docker run -ti -e AWS_PROFILE=$(AWS_PROFILE) -v $(CURDIR):/var/task -v ~/.aws/:/root/.aws  --rm mligus/zappa:python3.6 bash
